language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging

  # Feed backend
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed mabdelgawad94/udagram-api-feed:latest

  # User backend
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user mabdelgawad94/udagram-api-user:latest

  # Frontend
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend mabdelgawad94/udagram-frontend:latest

  # User backend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy mabdelgawad94/udagram-reverseproxy:latest

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mabdelgawad94/udagram-api-feed:latest
  - docker push mabdelgawad94/udagram-api-user:latest
  - docker push mabdelgawad94/udagram-frontend:latest
  - docker push mabdelgawad94/udagram-reverseproxy:latest
